///////////////////////////////////////////////////////////////////////////////
// mainClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "mainClassFactory.h"
#include "mainServices.h"
#include "mainVersion.h"
#include "Module1.h"

BEGIN_CLASS_MAP(CmainClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_mainCModule1, SRVNAME_MAIN "!CModule1", CModule1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CmainClassFactory::CmainClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_MAIN)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(main));
#endif //defined(TCDBG_UNIT_VERSION)
}

