///////////////////////////////////////////////////////////////////////////////
// mainInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "mainServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
