///////////////////////////////////////////////////////////////////////////////
// mainServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_main = 0x3F000000;
#define SRVNAME_MAIN "main"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_mainCModule1 = {0xf0a9e885,0x14d1,0x43ce,{0x8d,0x82,0xfb,0x18,0x1e,0x5c,0x28,0x99}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1Parameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Parameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Module1Parameter, *PModule1Parameter;

typedef struct _Module1Inputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} Module1Inputs, *PModule1Inputs;

typedef struct _Module1Outputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} Module1Outputs, *PModule1Outputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
